### ISSUE TITLE
Compiler Error

### ISSUE THREAD

**Issue by adamj-w** [Menotdan/DripOS#14]
I have cloned the repo and added an i686 elf compiler to the mix. Changed the Makefile to have the CC and GDB variables to point to the right file location, but when I tried to make it gave me an error saying the command was not found. I think this has to do with the fact that the makefile doesn't even use the CC command to compile and also doesn't have a linker variable.
![photo](https://user-images.githubusercontent.com/15058190/50195647-a20d2100-0305-11e9-8fec-344187977e43.png)
There is a bin folder and programs inside that

**Comment by szymex73** [comment]
Use the full path to the files inside Makefile and check if it works

**Comment by adamj-w** [comment]
The problem has to do with the makefile not with the directory when I changed all occurrences of i686-elf-gcc to ${CC} I was able to compile.

**Comment by szymex73** [comment]
Ok, that makes sense.
I need to change the makefile a bit

**Comment by Menotdan** [comment]
> I have cloned the repo and added an i686 elf compiler to the mix. Changed the Makefile to have the CC and GDB variables to point to the right file location, but when I tried to make it gave me an error saying the command was not found. I think this has to do with the fact that the makefile doesn't even use the CC command to compile and also doesn't have a linker variable.
> ![photo](https://user-images.githubusercontent.com/15058190/50195647-a20d2100-0305-11e9-8fec-344187977e43.png)
> There is a bin folder and programs inside that

well you could add to bin path to ur path, thats what i have
