### ISSUE TITLE
Shell

### ISSUE THREAD

**Issue by BasToTheMax** [Menotdan/DripOS#25]
Does it include a shell / terminal?

**Comment by Menotdan** [comment]
It doesn't include anything, everything is in userspace application which I haven't put anywhere. Also, the code is broken ATM and I haven't gotten around to fixing it.

**Comment by BasToTheMax** [comment]
Okay. Should I try to make my own OS? Do you have any recommendations for me?

**Comment by Menotdan** [comment]
> Should I try to make my own OS?
It depends on how comfortable you are with computing concepts and programming languages. If you don't really know anything about those topics, it would be extremely beneficial to learn them first.
